version: '3.8'

services:
  db:
    container_name: db-cookies-heart
    image: postgres:13
    volumes:
      - cookies_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cookiesheartdb
    ports:
      - "5433:5432"
    networks:
      - webapp_network

  backend:
    container_name: backend-cookies-heart
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/cookiesheartdb
      - DEBUG=True
    networks:
      - webapp_network

  ui:
    container_name: ui-cookies-heart
    build: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5174:5173"
    depends_on:
      - backend
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:8001
    networks:
      - webapp_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-cookies-heart
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db
    networks:
      - webapp_network

networks:
  webapp_network:
    driver: bridge

volumes:
  cookies_postgres_data:
